// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn2R9vTRyZtl3phnZJXp3xZ1lf3h56rd4',
    appId: '1:60665447741:web:d63b67bacc0e9549ac7154',
    messagingSenderId: '60665447741',
    projectId: 'learntocareer-20406',
    authDomain: 'learntocareer-20406.firebaseapp.com',
    storageBucket: 'learntocareer-20406.appspot.com',
    measurementId: 'G-2ZMLG929V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MJ4_cPz_Zw8lNHeLYT4nO8RZUsaeuZ0',
    appId: '1:60665447741:android:bf3f296ea845c2a9ac7154',
    messagingSenderId: '60665447741',
    projectId: 'learntocareer-20406',
    storageBucket: 'learntocareer-20406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAelFV956N0H28_8diPvUYBwgwrbNhu0mM',
    appId: '1:60665447741:ios:24889088899d7c82ac7154',
    messagingSenderId: '60665447741',
    projectId: 'learntocareer-20406',
    storageBucket: 'learntocareer-20406.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAelFV956N0H28_8diPvUYBwgwrbNhu0mM',
    appId: '1:60665447741:ios:24889088899d7c82ac7154',
    messagingSenderId: '60665447741',
    projectId: 'learntocareer-20406',
    storageBucket: 'learntocareer-20406.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn2R9vTRyZtl3phnZJXp3xZ1lf3h56rd4',
    appId: '1:60665447741:web:d9d2c72bd322734bac7154',
    messagingSenderId: '60665447741',
    projectId: 'learntocareer-20406',
    authDomain: 'learntocareer-20406.firebaseapp.com',
    storageBucket: 'learntocareer-20406.appspot.com',
    measurementId: 'G-HT52QGHPR1',
  );
}
